[project]
name = "llms"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "hf-xet>=1.1.5",
    "ruff>=0.12.5",
    "torch>=2.7.1",
    "transformers>=4.54.0",
]
